name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: sudo apt install libgtk-3-dev -y; sudo apt-get install -y libsoup2.4-1
    - name: Build
      run: cargo build --verbose
      working-directory: ./src-tauri
    - name: Run tests
      run: cargo test --verbose
      working-directory: ./src-tauri
      
