name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Apt Update
      run: sudo apt update
    - name: Install GTK3-Dev
      run: sudo apt install -y libgtk-3-dev libjavascriptcoregtk-4.0-bin libjavascriptcoregtk-4.0-dev libjavascriptcoregtk-4.0-18 libjavascriptcoregtk-4.0-bin
    - name: Install LibSoup
      run: sudo apt-get install -y libsoup2.4-dev libsoup2.4-1
    - name: Build
      run: cargo build --verbose
      working-directory: ./src-tauri
    - name: Run tests
      run: cargo test --verbose
      working-directory: ./src-tauri
      
